// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using distancing.Infastructure.Data;

namespace distancing.Migrations
{
    [DbContext(typeof(NetworkContext))]
    [Migration("20200627215419_NetworkName")]
    partial class NetworkName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("distancing.Models.Network+NetworkGraph", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("networkName")
                        .HasColumnType("TEXT");

                    b.Property<string>("schema")
                        .HasColumnType("TEXT");

                    b.Property<string>("shortId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("updateCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("NetworkGraph");
                });
#pragma warning restore 612, 618
        }
    }
}
